%ifndef __ANRC__CLIB_CONSTS_INTERNAL_INC__
%define __ANRC__CLIB_CONSTS_INTERNAL_INC__

extern cc_get_stdin
extern cc_get_stdout
extern cc_get_stderr

extern cc_get_SEEK_SET
extern cc_get_SEEK_CUR
extern cc_get_SEEK_END

extern cc_get__IONBF
extern cc_get__IOLBF
extern cc_get__IOFBF

extern cc_get_BUFSIZ
extern cc_get_EOF

extern cc_get_LC_ALL
extern cc_get_LC_COLLATE
extern cc_get_LC_CTYPE
extern cc_get_LC_MONETARY
extern cc_get_LC_NUMERIC
extern cc_get_LC_TIME

extern cc_get_MB_CUR_MAX

extern cc_get_RAND_MAX

%endif
